[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SimODEs_BioSB = "5388f2f4-6f5d-407b-91b8-8fea2d6a81e4"
