name = "SimODEs_BioSB"
uuid = "5388f2f4-6f5d-407b-91b8-8fea2d6a81e4"
authors = ["s136769 "]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Optimization = "5.2.0"
OptimizationOptimJL = "0.4.8"
OrdinaryDiffEq = "6.105.0"
Plots = "1.41.3"
QuasiMonteCarlo = "0.3.3"
Random = "1.11.0"
Sobol = "1.5.0"
StaticArrays = "1.9.15"
Statistics = "1.11.1"
