name = "SimODEs_BioSB"
uuid = "5388f2f4-6f5d-407b-91b8-8fea2d6a81e4"
authors = ["s136769 "]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
OrdinaryDiffEq = "6.105.0"
Plots = "1.41.3"
StaticArrays = "1.9.15"
